name = "Signaling"
uuid = "bcd52e29-c99a-484a-b924-8efabe89b5a3"
authors = ["Fatimetou El Bah <fatis.abd@hotmail.com>"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
